export const COLLECTIONS = {
  USERS: 'users',
  ROOMS: 'rooms',
  BOOKINGS: 'bookings',
  REVIEWS: 'reviews',
  FAVORITES: 'favorites',
  AVAILABILITY: 'availability',
  ACTIVITY_LOGS: 'activity_logs',
  COUPONS: 'coupons',
  PAYMENTS: 'payments',
  OTPS: 'otps',
  NEARBY_LOCATIONS: 'nearby_locations',
  GALLERY: 'gallery',
  PASSWORD_RESETS: 'password_resets',
} as const;
